### ISSUE TITLE
API Version Issues?

### ISSUE THREAD

**Issue by bharp28** [aws-samples/aws-securityhub-jira-software-integration#1]
Currently getting this error when trying to create the issue from Security Hub. I get the feeling that the issue is related to the API version.  Is there a way to change from version 2 to version 3?  I am using Jira Cloud and can see the API call, but we are not seeing any issues being created due to this error.

[ERROR] JIRAError: JiraError HTTP 400 url: https://<name>.atlassian.net/rest/api/2/issue
	text: Specify the Priority (name) in the string format
	response text = 
{
    "errorMessages": [],
    "errors": {
        "priority": "Specify the Priority (name) in the string format"
    }
}

Traceback (most recent call last):
  File "/var/task/security_hub_integration.py", line 85, in lambda_handler
    create_jira(jira_client, project_key, issuetype_name, product_arn, account,
  File "/var/task/security_hub_integration.py", line 40, in create_jira
    new_issue = utils.create_ticket(
  File "/var/task/utils.py", line 172, in create_ticket
    new_issue = jira_client.create_issue(
  File "/var/task/jira/client.py", line 1448, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "/var/task/jira/resilientsession.py", line 198, in post
    return self.__verb("POST", str(url), data=data, json=json, **kwargs)
  File "/var/task/jira/resilientsession.py", line 189, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/var/task/jira/resilientsession.py", line 64, in raise_on_error
    raise JIRAError(

**Comment by bharp28** [comment]
We were able to get this working. Our priority types were not matching the string that was being generated on the AWS side. Once we got the priority name in Jira to match what was being sent from the AWS side we started to see tickets generated.

**Comment by rinaudjaws** [comment]
Great to hear its working, thank you for providing the update!
