### ISSUE TITLE
[ERROR] Runtime.ImportModuleError

### ISSUE THREAD

**Issue by oaltalabani** [aws-samples/aws-securityhub-jira-software-integration#2]
Currently experiencing the following error when following readme and linked documentation:

https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/bidirectionally-integrate-aws-security-hub-with-jira-software.html

Please advise if there is any additional information that could be useful to help resolve this.

**Comment by sam-fakhreddine** [comment]
Switch the runtime to Python3.11

**Comment by rinaudjaws** [comment]
Thanks, I've updated the Python dependencies.
